### ISSUE TITLE
There sentence - omitting the name generates a Syntax error

### ISSUE THREAD

**Issue by DrunkBlood** [fujaba/fulibScenarios#226]
**Describe the bug**
In the definiton of the "There sentence" it says that one can omit the object name. Testing the example on fulib.org it threw a syntax error.
`syntax: missing {'attribute', 'Every', 'false', 'link', 'match', 'matches', 'some', 'true', 'type', 'where', 'whose', WORD} at '.'
1 error generated.`

**To Reproduce**
1. Goto fulib.org
2. Create a new scenario with any title.
3. Add `There is the university.`

**Expected behavior**
I would expect a class called University in the class diagram and an object university in the object diagram. Booth with no attributes. There would be this code generated `University university = new University();`.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10619180/111967128-f496a280-8af7-11eb-940d-33339b2fdeb3.png)

**Additional context**
Tested 22.03.2021

**Comment by Clashsoft** [comment]
Thanks for the report. This is actually intended behaviour, you use `a` to infer the variable name from the type and `the` to provide an explicit name. The [Complex Definitions](https://fulib.org/?example=Complex%20Definitions) example has two sentences that illustrate this:

```
There is a University.
There is the University Uni Kassel.
```

I agree that the syntax error is a bit misleading, in this case it just means that any identifier/name/word is expected. `attribute`, `Every`, etc. happen to be contextual keywords that can also be used as identifiers in most contexts, hence the rather long list of suggestions.
